nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173'] # Adjust this to your frontend URL
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE','PATCH', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': ~